# Generated by Django 4.0.3 on 2022-04-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcartProducts', '0005_orderitem_vistaid_orderitem_checksum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='VISTAid',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='checksum',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='order',
            name='VISTAid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='checksum',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='complete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
