# Generated by Django 4.0.3 on 2022-04-03 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcartProducts', '0006_remove_orderitem_vistaid_remove_orderitem_checksum_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_created',
            new_name='date_ordered',
        ),
    ]
