# Generated by Django 4.0.3 on 2022-04-03 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcartProducts', '0007_rename_date_created_order_date_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='VISTAid',
        ),
    ]
