# Generated by Django 4.0.3 on 2022-04-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcartProducts', '0008_remove_order_vistaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(choices=[('#1', 'Administration'), ('#2', 'Product Issue'), ('#3', 'PAY ISSUE ')], default=1, max_length=10000),
        ),
    ]
