# Generated by Django 4.0.3 on 2022-04-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcartProducts', '0011_rename_post_image_post_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=10000),
        ),
    ]
