# Generated by Django 4.0.3 on 2022-04-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcartProducts', '0018_remove_orderitem_status_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='checksum',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
