# Generated by Django 4.0.3 on 2022-04-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcartProducts', '0021_product_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='checksum',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
