# Generated by Django 4.0.4 on 2022-05-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcartProducts', '0026_shippingaddress_remove_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Complete', 'Complete'), ('OnTheWay', 'On the way'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded')], default='Pending', max_length=100, null=True),
        ),
    ]
