# Generated by Django 4.0.4 on 2022-05-29 04:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EcartProducts', '0028_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='product', to=settings.AUTH_USER_MODEL),
        ),
    ]
