# Generated by Django 4.0.4 on 2022-05-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcartProducts', '0029_alter_product_liked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order', models.CharField(blank=True, max_length=500, null=True)),
                ('TXN', models.CharField(blank=True, max_length=500, null=True)),
                ('Bank_TXN', models.CharField(blank=True, max_length=500, null=True)),
                ('Amount', models.CharField(blank=True, max_length=500, null=True)),
                ('Currency', models.CharField(blank=True, max_length=500, null=True)),
                ('Status', models.CharField(blank=True, max_length=500, null=True)),
                ('RESPCODE', models.CharField(blank=True, max_length=500, null=True)),
                ('RESPMSG', models.CharField(blank=True, max_length=500, null=True)),
                ('TXN_DATE', models.CharField(blank=True, max_length=500, null=True)),
                ('GATEWAYNAME', models.CharField(blank=True, max_length=500, null=True)),
                ('BANKNAME', models.CharField(blank=True, max_length=500, null=True)),
                ('PAYMENTMODE', models.CharField(blank=True, max_length=500, null=True)),
                ('CHECKSUMHASH', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
