# Generated by Django 4.0.4 on 2022-05-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcartProducts', '0031_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='Feedack',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='Reason',
            field=models.CharField(choices=[('Defect', 'Defect'), ('Wrong_Product', 'Wrong Product'), ('Not_Delivered_But_Paid', 'Not Delivered But Paid'), ('Not_Delivered_on_Time', 'Not Delivered on Time')], max_length=100, null=True),
        ),
    ]
