# Generated by Django 4.0.4 on 2022-05-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcartProducts', '0032_refund_feedack_alter_refund_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='Feedack',
        ),
        migrations.AddField(
            model_name='refund',
            name='Feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
