# Generated by Django 4.0.4 on 2022-05-29 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EcartProducts', '0033_remove_refund_feedack_refund_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='order_refund',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='EcartProducts.orderitem'),
            preserve_default=False,
        ),
    ]
